version: '3'

services:
  tcserv:
   image: tomcat
   ports:
     - 8080
   environment:
     - SERVICE_PORTS=8080
   volumes:
     - /app/webapps:/usr/local/tomcat/webapps/
     - /app/logs:/usr/local/tomcat/logs
     - /app/conf/tomcat/server.xml:/usr/local/tomcat/conf/server.xml
   deploy:
     replicas: 10
     update_config:
       parallelism: 5
       delay: 10s
     restart_policy:
       condition: on-failure
       max_attempts: 3
       window: 120s
   networks:
     - web

  proxy:
    image: dockercloud/haproxy
    depends_on:
      - tcserv
    environment:
      - BALANCE=leastconn
      - CERT_FOLDER=/host-certs/
      - VIRTUAL_HOST=https://*
      - RSYSLOG_DESTINATION=10.0.0.6:514
      - EXTRA_GLOBAL_SETTINGS=ssl-default-bind-options no-tlsv10

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /app/certs/haproxy:/host-certs
    ports:
      - 443:443
      - 80:80
    networks:
      - web
    deploy:
      placement:
        constraints: [node.role == manager]

networks:
  web:
    driver: overlay
